import unittest
from common.models import GatewayNode, SensorRecord
from common.crypto_utils import H, random_int, enc_sym, pack_fields
from auth_registration.registration import user_registration_phase
from auth_login.login import (
    user_login_request, 
    gateway_login_processing, 
    sensor_login_processing, 
    gateway_response_processing, 
    user_final_verification
)

class TestSecurityAttacks(unittest.TestCase):
    def setUp(self):
        # 1. Setup System
        self.e = 65537
        p = (1 << 127) - 1
        q = (1 << 61) - 1
        self.n = p * q
        phi = (p - 1) * (q - 1)
        self.dx = pow(self.e, -1, phi)
        self.n0 = 256
        self.gwn = GatewayNode(e=self.e, n=self.n, dx=self.dx, n0=self.n0)
        
        # 2. Register Legitimate User
        self.ID = "Alice"
        self.PW = "Password123"
        self.card = user_registration_phase(self.gwn, self.ID, self.PW)
        
        # 3. Register Sensor
        self.SID = "Sensor1"
        self.Pj_key = H(self.SID, self.gwn.dx)
        self.sensor_rec = SensorRecord(SID=self.SID, Pj=self.Pj_key)
        self.gwn.sensor_db[self.SID] = self.sensor_rec

    def test_replay_attack_login(self):
        """
        Attacker replays a captured valid Login Request (Step 1).
        Attacker DOES NOT know 'ri' (ephemeral secret).
        """
        # 1. Capture valid request
        valid_req = user_login_request(self.card, self.ID, self.PW)
        captured_Xi = valid_req["Xi"]
        
        # 2. Replay it to GWN (Attacker mimics User)
        # GWN accepts it (in this state-less protocol version, or if replay check missing)
        gw_out = gateway_login_processing(self.gwn, valid_req)
        self.assertIsNotNone(gw_out, "GWN might accept replay if no nonce cache, but Attacker must fail next")
        
        # 3. Sensor accepts it
        sensor_out = sensor_login_processing(self.sensor_rec, gw_out)
        self.assertIsNotNone(sensor_out)
        
        # 4. GWN returns response
        gw_resp = gateway_response_processing(self.gwn, gw_out["gw_state"], sensor_out)
        
        # 5. Attacker tries to derive Session Key
        # Attacker sees gw_resp["Xj"] (encrypted with User Public Key)
        # Attacker needs 'di' and 'ni' to decrypt Xj -> rj'
        # BUT 'di' and 'ni' were generated by the User in Step 1 and kept internal.
        # The Attacker, even replaying the message, does NOT have the internal state 'di', 'ni', 'ri' 
        # that matches the 'Xi' sent in the replayed message.
        
        # IF Attacker tries to use their OWN 'di_fake', 'ni_fake':
        # They can't, because Xi was generated from 'ri' and GWN uses 'ni' sent in request.
        # Wait, 'ni' IS sent in the request (plaintext-ish? No, D0 uses ni in hash).
        # Actually 'ni' is sent in M1 or simply passed?
        # In `user_login_request`:
        # D0 = Enc(..., ni)
        # M1 = H(..., ni, ...)
        # ni is returned in the dict `valid_req["ni"]`.
        
        # So Attacker knows 'ni'. But they don't know 'di' (Private Key).
        # So they cannot decrypt Xj.
        
        Xj = gw_resp["Xj"]
        
        # Attacker tries to decrypt Xj without di
        # They fail to get rj_prime
        # SK = H(ri, rj_prime, Xi, Xj)
        # They also don't know 'ri' (which is inside Xi).
        
        # We assert that without ri and di, SK cannot be derived.
        # We simulate Attacker guessing:
        ri_guess = random_int(128)
        rj_guess = random_int(128)
        
        sk_attacker = H(ri_guess, rj_guess, captured_Xi, Xj)
        
        # Legitimate User
        sk_user = user_final_verification(valid_req, self.card, gw_resp)
        
        self.assertNotEqual(sk_attacker, sk_user, "Replay Attacker should not derive valid SK")

    def test_user_impersonation_wrong_password(self):
        """
        Attacker tries to generate login request with wrong password.
        """
        # Attacker knows ID but guesses PW
        fake_PW = "Wrong123"
        
        # Attempt to run logic manually or via function
        # The function `user_login_request` performs a local check `A' == Ai`.
        # If attacker steals smart card BUT doesn't know PW:
        req = user_login_request(self.card, self.ID, fake_PW)
        
        self.assertIsNone(req, "Smart Card should reject wrong password locally")

    def test_gateway_impersonation(self):
        """
        Attacker impersonates GWN to User.
        """
        # User sends Step 1
        req = user_login_request(self.card, self.ID, self.PW)
        
        # Attacker intercepts and sends fake Step 4 response
        # Need M4, D5, Xj
        # M4 = H(D5, Ci, Xj, ri)
        # D5 = H(SKj, Xj, ri) -- Wait, D5 comes from Sensor usually
        
        # Attacker generates random Xj
        Xj_fake = random_int(128)
        D5_fake = random_int(128)
        M4_fake = random_int(128) # Random guess
        
        gw_resp_fake = {
            "M4": M4_fake,
            "D5": D5_fake,
            "Xj": Xj_fake
        }
        
        # User verifies
        sk = user_final_verification(req, self.card, gw_resp_fake)
        self.assertIsNone(sk, "User should reject Fake Gateway response (M4 mismatch)")

    def test_sensor_impersonation(self):
        """
        Attacker impersonates Sensor to GWN.
        """
        # User -> GWN
        req = user_login_request(self.card, self.ID, self.PW)
        gw_out = gateway_login_processing(self.gwn, req)
        
        # Attacker intercepts gw_out and tries to send Sensor Response (Step 3)
        # GWN expects M3 = H(Xj, Pj, rn, ri, ei)
        # Attacker does NOT know Pj (Shared Secret with Sensor)
        
        Xj_fake = random_int(128)
        M3_fake = random_int(128) # Guess
        D5_fake = random_int(128)
        
        sensor_resp_fake = {
            "M3": M3_fake,
            "D5": D5_fake,
            "Xj": Xj_fake,
            "SKj": None 
        }
        
        # GWN processes
        gw_resp = gateway_response_processing(self.gwn, gw_out["gw_state"], sensor_resp_fake)
        self.assertIsNone(gw_resp, "GWN should reject Fake Sensor response (M3 mismatch)")

    def test_privileged_insider_attack(self):
        """
        User C tries to impersonate User A?
        Or GWN Insider?
        Let's test if a Registered User (Eve) can impersonate Alice.
        """
        # Register Eve
        card_eve = user_registration_phase(self.gwn, "Eve", "EvePW")
        
        # Eve wants to impersonate Alice
        # She generates a request using HER keys but tries to perform identity theft
        # Generates request as Eve first to get valid crypto structures
        req_eve = user_login_request(card_eve, "Eve", "EvePW")
        
        # Eve modifies the cleartext payload before encryption inside D0?
        # No, she has to generate D0 herself.
        
        # D0 = Enc_key(ID || Ci)
        # key = H(ri, Xi, ni) - Eve knows these for her request
        
        # Eve tries to pack "Alice" with her own "Ci_eve"
        # (She doesn't know Alice's Ci, so she hopes GWN doesn't bind Ci to ID strongly? 
        # But GWN recalculates Ci* = H(ID, dx, r) and compares with decrypted Ci)
        
        # 1. Eve prepares ID="Alice"
        # 2. Eve keys D0 using her current process
        ri = req_eve["ri"]
        Xi = req_eve["Xi"]
        ni = req_eve["ni"]
        mask_D0 = H(ri, Xi, ni)
        
        Ci_eve = req_eve["Ci_prime"] # This is Eve's Ci
        
        # Packing "Alice" with Eve's Ci
        plaintext_D0_fake = pack_fields("Alice", Ci_eve)
        D0_fake = enc_sym(mask_D0, plaintext_D0_fake)
        
        # Eve replaces D0 in her request
        req_eve["D0"] = D0_fake
        
        # Eve also needs to update M1 if M1 covers ID
        # M1 = H(Xi, ri, ei, ni, ID, Ci)
        # Eve updates M1 to cover "Alice"
        req_eve["M1"] = H(Xi, ri, req_eve["ei"], ni, "Alice", Ci_eve)
        
        # Eve sends this forged request to GWN
        gw_out = gateway_login_processing(self.gwn, req_eve)
        
        # GWN decrypts D0 -> finds ID="Alice"
        # GWN looks up "Alice"
        # GWN calculates Ci* = H("Alice", dx, r_alice)
        # GWN compares Ci* with Ci_eve
        # They should NOT match.
        
        self.assertIsNone(gw_out, "GWN should reject Insider Attack (Ci mismatch)") 

if __name__ == '__main__':
    unittest.main()
