from registration import random_int, user_registration_phase, GatewayNode

# -----------------------------
# Example usage / demo
# -----------------------------
if __name__ == "__main__":
    # 1) GWN initialization
    # In a real system, RSA keys are generated by a crypto library.
    # Here, we just pick some dummy numbers to illustrate.
    e = 65537
    n = random_int(2048)   # dummy "modulus"
    dx = random_int(2048)  # dummy "private exponent"
    n0 = 2**8              # example medium integer: 2^4 <= n0 <= 2^8

    gwn = GatewayNode(e=e, n=n, dx=dx, n0=n0)

    # 2) User chooses ID and password and runs auth_registration
    IDi = "alice123"
    PWi = "SuperSecurePassword!"

    smart_card = user_registration_phase(gwn, IDi, PWi)

    print("=== Smart Card Issued to User ===")
    print(f"Ai        = {smart_card.Ai}")
    print(f"Bi        = {smart_card.Bi}")
    print(f"n0        = {smart_card.n0}")
    print(f"n         = {smart_card.n}")
    print(f"e         = {smart_card.e}")
    print(f"ai ⊕ Ai   = {smart_card.ai_xor_Ai}")
    print(f"b (local) = {smart_card.b}")

    print("\n=== GWN Database Entry ===")
    record = gwn.user_db[IDi]
    print(f"IDi       = {record.IDi}")
    print(f"r         = {record.r}")
    print(f"ai        = {record.ai}")
    print(f"HoneyList = {record.honey_list}")
